// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

library ioctl_terminal_mojom;

import 'dart:async';

import 'package:mojo/bindings.dart' as bindings;
import 'package:mojo/core.dart' as core;
const int kIoctlTerminalInvalid = 0;
const int kIoctlTerminalGetSettings = 1;
const int kIoctlTerminalSetSettings = 2;
const int kIoctlTerminalGetWindowSize = 3;
const int kIoctlTerminalSetWindowSize = 4;
const int kIoctlTerminalTermiosBaseFieldCount = 6;
const int kIoctlTerminalTermiosIFlagIndex = 0;
const int kIoctlTerminalTermiosOFlagIndex = 1;
const int kIoctlTerminalTermiosCFlagIndex = 2;
const int kIoctlTerminalTermiosLFlagIndex = 3;
const int kIoctlTerminalTermiosISpeedIndex = 4;
const int kIoctlTerminalTermiosOSpeedIndex = 5;
const int kIoctlTerminalTermiosCtrlCharCount = 17;
const int kIoctlTerminalTermiosCtrlCharVintrIndex = 17;
const int kIoctlTerminalTermiosCtrlCharVquitIndex = 18;
const int kIoctlTerminalTermiosCtrlCharVeraseIndex = 19;
const int kIoctlTerminalTermiosCtrlCharVkillIndex = 20;
const int kIoctlTerminalTermiosCtrlCharVeofIndex = 21;
const int kIoctlTerminalTermiosCtrlCharVtimeIndex = 22;
const int kIoctlTerminalTermiosCtrlCharVminIndex = 23;
const int kIoctlTerminalTermiosCtrlCharVswtcIndex = 24;
const int kIoctlTerminalTermiosCtrlCharVstartIndex = 25;
const int kIoctlTerminalTermiosCtrlCharVstopIndex = 26;
const int kIoctlTerminalTermiosCtrlCharVsuspIndex = 27;
const int kIoctlTerminalTermiosCtrlCharVeolIndex = 28;
const int kIoctlTerminalTermiosCtrlCharVreprintIndex = 29;
const int kIoctlTerminalTermiosCtrlCharVdiscardIndex = 30;
const int kIoctlTerminalTermiosCtrlCharVweraseIndex = 31;
const int kIoctlTerminalTermiosCtrlCharVlnextIndex = 32;
const int kIoctlTerminalTermiosCtrlCharVeoL2Index = 33;
const int kIoctlTerminalTermiosIFlagIgnbrk = 0x0001;
const int kIoctlTerminalTermiosIFlagBrkint = 0x0002;
const int kIoctlTerminalTermiosIFlagIgnpar = 0x0004;
const int kIoctlTerminalTermiosIFlagParmrk = 0x0008;
const int kIoctlTerminalTermiosIFlagInpck = 0x0010;
const int kIoctlTerminalTermiosIFlagIstrip = 0x0020;
const int kIoctlTerminalTermiosIFlagInlcr = 0x0040;
const int kIoctlTerminalTermiosIFlagIgncr = 0x0080;
const int kIoctlTerminalTermiosIFlagIcrnl = 0x0100;
const int kIoctlTerminalTermiosIFlagIuclc = 0x0200;
const int kIoctlTerminalTermiosIFlagIxon = 0x0400;
const int kIoctlTerminalTermiosIFlagIxany = 0x0800;
const int kIoctlTerminalTermiosIFlagIxoff = 0x1000;
const int kIoctlTerminalTermiosIFlagImaxbel = 0x2000;
const int kIoctlTerminalTermiosIFlagIutF8 = 0x4000;
const int kIoctlTerminalTermiosOFlagOpost = 0x0001;
const int kIoctlTerminalTermiosOFlagOlcuc = 0x0002;
const int kIoctlTerminalTermiosOFlagOnlcr = 0x0004;
const int kIoctlTerminalTermiosOFlagOcrnl = 0x0008;
const int kIoctlTerminalTermiosOFlagOnocr = 0x0010;
const int kIoctlTerminalTermiosOFlagOnlret = 0x0020;
const int kIoctlTerminalTermiosOFlagOfill = 0x0040;
const int kIoctlTerminalTermiosOFlagOfdel = 0x0080;
const int kIoctlTerminalTermiosOFlagNldly = 0x0100;
const int kIoctlTerminalTermiosOFlagNL0 = 0x0000;
const int kIoctlTerminalTermiosOFlagNL1 = 0x0100;
const int kIoctlTerminalTermiosOFlagCrdly = 0x0600;
const int kIoctlTerminalTermiosOFlagCR0 = 0x0000;
const int kIoctlTerminalTermiosOFlagCR1 = 0x0200;
const int kIoctlTerminalTermiosOFlagCR2 = 0x0400;
const int kIoctlTerminalTermiosOFlagCR3 = 0x0600;
const int kIoctlTerminalTermiosOFlagTabdly = 0x1800;
const int kIoctlTerminalTermiosOFlagTaB0 = 0x0000;
const int kIoctlTerminalTermiosOFlagTaB1 = 0x0800;
const int kIoctlTerminalTermiosOFlagTaB2 = 0x1000;
const int kIoctlTerminalTermiosOFlagTaB3 = 0x1800;
const int kIoctlTerminalTermiosOFlagBsdly = 0x2000;
const int kIoctlTerminalTermiosOFlagBS0 = 0x0000;
const int kIoctlTerminalTermiosOFlagBS1 = 0x2000;
const int kIoctlTerminalTermiosOFlagVtdly = 0x4000;
const int kIoctlTerminalTermiosOFlagVT0 = 0x0000;
const int kIoctlTerminalTermiosOFlagVT1 = 0x4000;
const int kIoctlTerminalTermiosOFlagFfdly = 0x8000;
const int kIoctlTerminalTermiosOFlagFF0 = 0x0000;
const int kIoctlTerminalTermiosOFlagFF1 = 0x8000;
const int kIoctlTerminalTermiosCFlagCsize = 0x0003;
const int kIoctlTerminalTermiosCFlagCS5 = 0x0000;
const int kIoctlTerminalTermiosCFlagCS6 = 0x0001;
const int kIoctlTerminalTermiosCFlagCS7 = 0x0002;
const int kIoctlTerminalTermiosCFlagCS8 = 0x0003;
const int kIoctlTerminalTermiosCFlagCstopb = 0x0004;
const int kIoctlTerminalTermiosCFlagCread = 0x0008;
const int kIoctlTerminalTermiosCFlagParenb = 0x0010;
const int kIoctlTerminalTermiosCFlagParodd = 0x0020;
const int kIoctlTerminalTermiosCFlagHupcl = 0x0040;
const int kIoctlTerminalTermiosCFlagClocal = 0x0080;
const int kIoctlTerminalTermiosLFlagIsig = 0x0001;
const int kIoctlTerminalTermiosLFlagIcanon = 0x0002;
const int kIoctlTerminalTermiosLFlagXcase = 0x0004;
const int kIoctlTerminalTermiosLFlagEcho = 0x0008;
const int kIoctlTerminalTermiosLFlagEchoe = 0x0010;
const int kIoctlTerminalTermiosLFlagEchok = 0x0020;
const int kIoctlTerminalTermiosLFlagEchonl = 0x0040;
const int kIoctlTerminalTermiosLFlagNoflsh = 0x0080;
const int kIoctlTerminalTermiosLFlagTostop = 0x0100;



